version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: starwars-backend-dev
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
    environment:
      - PYTHONPATH=/app
    networks:
      - starwars-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: starwars-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes file watching issues in Docker on some systems
    networks:
      - starwars-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:stable-alpine
    container_name: starwars-nginx-dev
    ports:
      - "6969:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    networks:
      - starwars-net

networks:
  starwars-net:
    driver: bridge
# Note: This docker-compose-dev.yml is tailored for development purposes.
# It includes live reloading for the frontend and backend, and mounts local directories.