version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: starwars-backend-dev
    ports:
      - "${BACKEND_PORT}:8000"
    working_dir: /app
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
    environment:
      - PYTHONPATH=/app
    networks:
      - starwars-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 

  frontend:
    build:
      context: ./frontend
    container_name: starwars-frontend-dev
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env 
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Fixes file watching issues in Docker on some systems
    networks:
      - starwars-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: starwars-nginx-dev
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - starwars-net
    restart: unless-stopped

networks:
  starwars-net:
    driver: bridge
# Note: This docker-compose-dev.yml is tailored for development purposes.
# It includes live reloading for the frontend and backend, and mounts local directories.